 const mockData = [
  {
    "page1" :[{
    id: 1,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "html.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 2,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "css.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 3,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "javascript.png",
    views: 20,
    likes: 20,
    comments: 20,
  }]
},
{
"page2" :[{
    id: 1,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "facebook.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 2,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "insta.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 3,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "whatsapp.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  }]
},
{
"page3" :[{
    id: 1,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "html.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 2,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "css.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 3,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "javascript.png",
    views: 20,
    likes: 20,
    comments: 20,
  }]
},
{
"page4" :[{
    id: 1,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "facebook.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 2,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "insta.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 3,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "whatsapp.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  }]
},{
"page5" :[{
    id: 1,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "html.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 2,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "css.jpeg",
    views: 20,
    likes: 20,
    comments: 20,
  },
  {
    id: 3,
    title: "Energy Efficiency ideas to improve business sustainability",
    excerpt: "Energy Efficiency with Business Sustainability for substantial savings.",
    author: "FAARUQ AZEEZ",
    date: "23 May, 2024",
    image: "javascript.png",
    views: 20,
    likes: 20,
    comments: 20,
  }]
}
];

export default mockData;